// Generated by https://quicktype.io

export interface WeatherForecast {
	latitude: number;
	longitude: number;
	generationtime_ms: number;
	utc_offset_seconds: number;
	timezone: string;
	timezone_abbreviation: string;
	elevation: number;
	current_units?: Partial<CurrentUnits>;
	current?: Partial<Current>;
	hourly_units?: Partial<HourlyUnits>;
	hourly?: Partial<Hourly>;
	daily_units?: Partial<DailyUnits>;
	daily?: Partial<Daily>;
}

export interface Current {
	time: string;
	interval: number;
	snowfall: number;
	showers: number;
	rain: number;
	precipitation: number;
	temperature_2m: number;
	relative_humidity_2m: number;
	apparent_temperature: number;
	is_day: number;
	surface_pressure: number;
	pressure_msl: number;
	cloud_cover: number;
	weather_code: number;
	wind_speed_10m: number;
	wind_direction_10m: number;
	wind_gusts_10m: number;
}

export interface CurrentUnits {
	time: string;
	interval: string;
	snowfall: string;
	showers: string;
	rain: string;
	precipitation: string;
	temperature_2m: string;
	relative_humidity_2m: string;
	apparent_temperature: string;
	is_day: string;
	surface_pressure: string;
	pressure_msl: string;
	cloud_cover: string;
	weather_code: string;
	wind_speed_10m: string;
	wind_direction_10m: string;
	wind_gusts_10m: string;
}

export interface Daily {
	time: Date[];
	et0_fao_evapotranspiration: number[];
	shortwave_radiation_sum: number[];
	wind_direction_10m_dominant: number[];
	wind_gusts_10m_max: number[];
	wind_speed_10m_max: number[];
	rain_sum: number[];
	showers_sum: number[];
	snowfall_sum: number[];
	precipitation_sum: number[];
	precipitation_hours: number[];
	precipitation_probability_max: number[];
	uv_index_clear_sky_max: number[];
	uv_index_max: number[];
	sunshine_duration: number[];
	daylight_duration: number[];
	sunset: string[];
	sunrise: string[];
	apparent_temperature_min: number[];
	apparent_temperature_max: number[];
	temperature_2m_min: number[];
	temperature_2m_max: number[];
	weather_code: number[];
}

export interface DailyUnits {
	time: string;
	et0_fao_evapotranspiration: string;
	shortwave_radiation_sum: string;
	wind_direction_10m_dominant: string;
	wind_gusts_10m_max: string;
	wind_speed_10m_max: string;
	rain_sum: string;
	showers_sum: string;
	snowfall_sum: string;
	precipitation_sum: string;
	precipitation_hours: string;
	precipitation_probability_max: string;
	uv_index_clear_sky_max: string;
	uv_index_max: string;
	sunshine_duration: string;
	daylight_duration: string;
	sunset: string;
	sunrise: string;
	apparent_temperature_min: string;
	apparent_temperature_max: string;
	temperature_2m_min: string;
	temperature_2m_max: string;
	weather_code: string;
}

export interface Hourly {
	time: string[];
	temperature_2m: number[];
	relative_humidity_2m: number[];
	dew_point_2m: number[];
	apparent_temperature: number[];
	precipitation_probability: number[];
	precipitation: number[];
	rain: number[];
	showers: number[];
	snowfall: number[];
	snow_depth: number[];
	vapour_pressure_deficit: number[];
	et0_fao_evapotranspiration: number[];
	evapotranspiration: number[];
	visibility: number[];
	cloud_cover_mid: number[];
	cloud_cover_high: number[];
	cloud_cover_low: number[];
	cloud_cover: number[];
	surface_pressure: number[];
	pressure_msl: number[];
	weather_code: number[];
	wind_speed_10m: number[];
	wind_speed_80m: number[];
	wind_speed_120m: number[];
	wind_speed_180m: number[];
	wind_direction_10m: number[];
	wind_direction_80m: number[];
	wind_direction_120m: number[];
	wind_gusts_10m: number[];
	wind_direction_180m: number[];
	temperature_120m: number[];
	temperature_80m: number[];
	temperature_180m: number[];
	soil_moisture_27_to_81cm: number[];
	soil_moisture_9_to_27cm: number[];
	soil_moisture_3_to_9cm: number[];
	soil_moisture_1_to_3cm: number[];
	soil_moisture_0_to_1cm: number[];
	soil_temperature_54cm: number[];
	soil_temperature_18cm: number[];
	soil_temperature_6cm: number[];
	soil_temperature_0cm: number[];
}

export interface HourlyUnits {
	time: string;
	temperature_2m: string;
	relative_humidity_2m: string;
	dew_point_2m: string;
	apparent_temperature: string;
	precipitation_probability: string;
	precipitation: string;
	rain: string;
	showers: string;
	snowfall: string;
	snow_depth: string;
	vapour_pressure_deficit: string;
	et0_fao_evapotranspiration: string;
	evapotranspiration: string;
	visibility: string;
	cloud_cover_mid: string;
	cloud_cover_high: string;
	cloud_cover_low: string;
	cloud_cover: string;
	surface_pressure: string;
	pressure_msl: string;
	weather_code: string;
	wind_speed_10m: string;
	wind_speed_80m: string;
	wind_speed_120m: string;
	wind_speed_180m: string;
	wind_direction_10m: string;
	wind_direction_80m: string;
	wind_direction_120m: string;
	wind_gusts_10m: string;
	wind_direction_180m: string;
	temperature_120m: string;
	temperature_80m: string;
	temperature_180m: string;
	soil_moisture_27_to_81cm: string;
	soil_moisture_9_to_27cm: string;
	soil_moisture_3_to_9cm: string;
	soil_moisture_1_to_3cm: string;
	soil_moisture_0_to_1cm: string;
	soil_temperature_54cm: string;
	soil_temperature_18cm: string;
	soil_temperature_6cm: string;
	soil_temperature_0cm: string;
}

// export interface WeatherForecast {
// 	latitude: number;
// 	longitude: number;
// 	generationtime_ms: number;
// 	utc_offset_seconds: number;
// 	timezone: string;
// 	timezone_abbreviation: string;
// 	elevation: number;
// 	current_units: CurrentUnits;
// 	current: Current;
// 	hourly_units: HourlyUnits;
// 	hourly: Hourly;
// 	daily_units: DailyUnits;
// 	daily: Daily;
// }

// export interface Current {
// 	time: number;
// 	interval: number;
// 	temperature_2m: number;
// 	weather_code: number;
// 	wind_speed_10m: number;
// }

// export interface CurrentUnits {
// 	time: string;
// 	interval: string;
// 	temperature_2m: string;
// 	weather_code: string;
// 	wind_speed_10m: string;
// }

// export interface Daily {
// 	time: number[];
// 	weather_code: number[];
// 	temperature_2m_max: number[];
// 	temperature_2m_min: number[];
// 	apparent_temperature_max: number[];
// 	apparent_temperature_min: number[];
// 	precipitation_sum: number[];
// }

// export interface DailyUnits {
// 	time: string;
// 	weather_code: string;
// 	temperature_2m_max: string;
// 	temperature_2m_min: string;
// 	apparent_temperature_max: string;
// 	apparent_temperature_min: string;
// 	precipitation_sum: string;
// }

// export interface Hourly {
// 	time: number[];
// 	temperature_2m: number[];
// 	apparent_temperature: number[];
// 	precipitation: number[];
// 	weather_code: number[];
// 	wind_speed_10m: number[];
// }

// export interface HourlyUnits {
// 	time: string;
// 	temperature_2m: string;
// 	apparent_temperature: string;
// 	precipitation: string;
// 	weather_code: string;
// 	wind_speed_10m: string;
// }

type DailyWeatherVariable =
	| 'temperature_2m_max'
	| 'temperature_2m_min'
	| 'weather_code'
	| 'apparent_temperature_max'
	| 'apparent_temperature_min'
	| 'sunrise'
	| 'sunset'
	| 'daylight_duration'
	| 'sunshine_duration'
	| 'uv_index_max'
	| 'uv_index_clear_sky_max'
	| 'showers_sum'
	| 'rain_sum'
	| 'snowfall_sum'
	| 'precipitation_sum'
	| 'precipitation_hours'
	| 'precipitation_probability_max'
	| 'et0_fao_evapotranspiration'
	| 'shortwave_radiation_sum'
	| 'wind_direction_10m_dominant'
	| 'wind_gusts_10m_max'
	| 'wind_speed_10m_max';

type HourlyWeatherVariable =
	| 'temperature_2m'
	| 'relative_humidity_2m'
	| 'dew_point_2m'
	| 'precipitation'
	| 'precipitation_probability'
	| 'apparent_temperature'
	| 'rain'
	| 'showers'
	| 'snowfall'
	| 'snow_depth'
	| 'vapour_pressure_deficit'
	| 'et0_fao_evapotranspiration'
	| 'evapotranspiration'
	| 'visibility'
	| 'cloud_cover_high'
	| 'cloud_cover_mid'
	| 'cloud_cover_low'
	| 'cloud_cover'
	| 'surface_pressure'
	| 'pressure_msl'
	| 'weather_code'
	| 'wind_speed_80m'
	| 'wind_speed_10m'
	| 'wind_speed_120m'
	| 'wind_speed_180m'
	| 'wind_direction_10m'
	| 'wind_direction_80m'
	| 'wind_direction_120m'
	| 'wind_direction_180m'
	| 'wind_gusts_10m'
	| 'temperature_80m'
	| 'temperature_120m'
	| 'temperature_180m'
	| 'soil_moisture_27_to_81cm'
	| 'soil_moisture_9_to_27cm'
	| 'soil_moisture_3_to_9cm'
	| 'soil_moisture_1_to_3cm'
	| 'soil_moisture_0_to_1cm'
	| 'soil_temperature_54cm'
	| 'soil_temperature_18cm'
	| 'soil_temperature_6cm'
	| 'soil_temperature_0cm'
	| 'uv_index'
	| 'uv_index_clear_sky'
	| 'is_day';

type CurrentWeatherVariable =
	| 'temperature_2m'
	| 'relative_humidity_2m'
	| 'apparent_temperature'
	| 'is_day'
	| 'snowfall'
	| 'showers'
	| 'rain'
	| 'precipitation'
	| 'weather_code'
	| 'cloud_cover'
	| 'pressure_msl'
	| 'surface_pressure'
	| 'wind_direction_10m'
	| 'wind_speed_10m'
	| 'wind_gusts_10m';

type TemperatureUnit = 'celcius' | 'fahrenheit';
type PrecipitationUnit = 'millimeter' | 'inch';

export interface GetWeatherForecastPayload {
	latitude: number;
	longitude: number;
	daily?: DailyWeatherVariable[];
	hourly?: HourlyWeatherVariable[];
	current?: CurrentWeatherVariable[];
	timezone?: string;
	past_days?: number;
	forecast_days?: number;
	/** Default: `celcius` */
	temperature_unit?: TemperatureUnit;
	/** Default: `millimeter` */
	precipitation_unit?: PrecipitationUnit;
}
